# $schema: https://json.schemastore.org/github-workflow.json
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: rbrownwsws/melange-workflows/.github/workflows/build.yaml@ec7e978e8938075f9697c8e0685037fa4b6cb7c5 # master
    with:
      build-arch: "amd64,arm64"
